services:
  app:
    build:
      context: .
    env_file:
      - path: ./env/docker.env
    ports:
      - 80:8080

  redis:
    image: docker.io/redis:7.4
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
