server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: personal-finance
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

jwt:
  duration: 60  # in minutes
  private:
    key: classpath:key/app.key
  public:
    key: classpath:key/app.pub

springdoc:
  swagger-ui:
    operationsSorter: method
    try-it-out-enabled: true

auth:
  username: ${USERNAME}
  password: ${PASSWORD}